version: "3.9"

services:
  frontend:
    container_name: next-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./fe.env
    depends_on:
      - backend

  backend:
    container_name: bun-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./be.env
    command: ["bun", "run", "src/serve.ts"]
